apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "2"
  creationTimestamp: null
  generation: 1
  labels:
    run: nodejs-deploy
  name: nodejs-deploy
  selfLink: /apis/extensions/v1beta1/namespaces//deployments/nodejs-deploy
spec:
  replicas: 5
  selector:
    matchLabels:
      run: nodejs-deploy
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        run: nodejs-deploy
    spec:
      containers:
      - command:
        - node
        - app/server.js
        image: asia.gcr.io/kubernetes-demo-172306/nodejs:2.0
        imagePullPolicy: IfNotPresent
        name: nodejs-deploy
        ports:
        - containerPort: 3000
          protocol: TCP
        resources:
          limits:
            cpu: 200m
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
status: {}
