apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    run: nodejs-deploy
  name: nodejs-deploy
  selfLink: /api/v1/namespaces//services/nodejs-deploy
spec:
  #clusterIP: <unknown>
  ports:
  - nodePort: 31828
    port: 80
    protocol: TCP
    targetPort: 3000
  selector:
    run: nodejs-deploy
  sessionAffinity: None
  type: LoadBalancer
status:
  loadBalancer: {}
