steps:
  - name: "gcr.io/cloud-builders/kubectl:7fa1c1756d8bc963f1a389f4a6937dc71f08ada2"
    env:
    - 'CLOUDSDK_COMPUTE_ZONE=asia-northeast1-a'
    - 'CLOUDSDK_CONTAINER_CLUSTER=gcb'
    - 'REV=$REVISION_ID'
    args: ["apply", "--namespace=default", -f", "/development"]
