steps:
  - name: "gcr.io/cloud-builders/kubectl"
    env:
    - 'CLOUDSDK_COMPUTE_ZONE=us-central1-a'
    - 'CLOUDSDK_CONTAINER_CLUSTER=gcb'
    - 'REV=$REVISION_ID'
    args: ["apply", "-f", "/development"]
